Repository rouge-ruby/rouge, pull requests merged in 2019-06, with the labels that each got.

#1141 Avoid creating a new array of strings simply to be checked against
  lib/rouge/lexer.rb
Labels: maintainer-action

#1137 Add a rake task to profile basic memory usage
  .travis.yml
  Gemfile
  Rakefile
Labels: author-action

#1083 resolves #1082 HTMLTable formatter delegates to format method of inner formatter
  lib/rouge/formatters/html_table.rb
  spec/formatters/html_linewise_spec.rb
Labels: author-action

#1053 Markdown code block fixes
  lib/rouge/lexers/markdown.rb
  spec/lexers/markdown_spec.rb
Labels: author-action

#1149 Introduce :detectable? singleton method for lexers
  lib/rouge/guessers/source.rb
  lib/rouge/lexer.rb
  spec/lexer_spec.rb
Labels: author-action

#1153 Add clarity to tests for Lexer.detectable?
  spec/lexer_spec.rb
Labels: needs-review

#1140 Avoid creating a new array on every Lexer.all call
  lib/rouge/lexer.rb
Labels: maintainer-action

#1152 Proposal for escaping within lexed content
  lib/rouge.rb
  lib/rouge/cli.rb
  lib/rouge/demos/escape
  lib/rouge/formatter.rb
  lib/rouge/formatters/html.rb
  lib/rouge/formatters/terminal256.rb
  lib/rouge/lexers/escape.rb
  spec/cli_spec.rb
  spec/formatter_spec.rb
  spec/lexers_spec.rb
  spec/visual/app.rb
  spec/visual/samples/escape
Labels: needs-review

#1085 resolves #1084 preserve newlines in linewise formatter
  lib/rouge/formatters/html_linewise.rb
  spec/formatters/html_linewise_spec.rb
Labels: maintainer-action

#749 Add SuperCollider language support
  lib/rouge/demos/supercollider
  lib/rouge/guessers/disambiguation.rb
  lib/rouge/lexers/supercollider.rb
  spec/lexers/python_spec.rb
  spec/lexers/supercollider_spec.rb
  spec/visual/samples/supercollider
Labels: author-action

#1160 Fix arbitrary delimiter regular expressions in Perl lexer
  lib/rouge/lexers/perl.rb
  spec/visual/samples/perl
Labels: needs-review

#1161 Fix backtracking issues, add string interpolation in Perl lexer
  lib/rouge/lexers/perl.rb
  spec/visual/samples/perl
Labels: needs-review

#1003 Add support for raw/verbatim blocks in Jinja/Twig
  lib/rouge/lexers/jinja.rb
  spec/visual/samples/jinja
  spec/visual/samples/twig
Labels: author-action

#1162 Rationalise visual sample for Perl
  spec/visual/samples/perl
Labels: needs-review

#1165 Fix escaping backslash in javascript lexer
  lib/rouge/lexers/javascript.rb
  spec/visual/samples/javascript
Labels: author-action

#1169 Fix errors in changelog
  CHANGELOG.md
Labels: author-action

#1167 Add Rake task for generating changelog entries
  Gemfile
  tasks/changelog.rake
Labels: author-action

#1159 Use predefined string when Lexer.debug_enabled?
  lib/rouge/lexer.rb
Labels: needs-review

#1044 Support for (Smallworld) Magik language
  lib/rouge/demos/magik
  lib/rouge/lexers/magik.rb
  spec/lexers/magik_spec.rb
  spec/visual/samples/magik
Labels: author-action

#1171 Fix wording and indentation in changelog Rake task
  tasks/changelog.rake
Labels: needs-review

#1173 only remove @debug_enabled if defined
  lib/rouge/lexer.rb
Labels: needs-review

#1174 fix warning when checking whether escape is enabled
  lib/rouge/formatter.rb
Labels: needs-review

#1037 Added BrainF*ck Language
  lib/rouge/demos/brainfuck
  lib/rouge/lexers/brainfuck.rb
  spec/lexers/brainfuck_spec.rb
  spec/visual/samples/brainfuck
Labels: author-action

#1184 Reset instance variable only if it is defined
  lib/rouge/lexer.rb
Labels: needs-review

#1172 Fix shebang regex in Python lexer
  lib/rouge/lexers/python.rb
  spec/lexers/python_spec.rb
Labels: needs-review

#1185 align style parameters in magritte theme
  lib/rouge/themes/magritte.rb
Labels: needs-review

#1177 Run rake tasks with interpreter warnings enabled
  .travis.yml
  Rakefile
Labels: author-action

#1190 Add issue templates
  .github/ISSUE_TEMPLATE/documentation-error.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/lexer-bug.md
  .github/ISSUE_TEMPLATE/lexer-request.md
  .github/ISSUE_TEMPLATE/lexing-bug.md
  .github/ISSUE_TEMPLATE/lexing-error.md
  .github/ISSUE_TEMPLATE/library-bug.md
Labels: needs-review

#830 Fix Prolog comment character
  lib/rouge/lexers/prolog.rb
  spec/visual/samples/prolog
Labels: bugfix-request

#1181 Style visual test app views
  spec/visual/app.rb
  spec/visual/templates/index.erb
  spec/visual/templates/layout.erb
  spec/visual/templates/lexer.erb
Labels: needs-review

#1189 Reduce 'character class has duplicated range' msgs
  lib/rouge/lexers/abap.rb
  lib/rouge/lexers/biml.rb
  lib/rouge/lexers/bsl.rb
  lib/rouge/lexers/ceylon.rb
  lib/rouge/lexers/conf.rb
  lib/rouge/lexers/crystal.rb
  lib/rouge/lexers/dart.rb
  lib/rouge/lexers/elixir.rb
  lib/rouge/lexers/elm.rb
  lib/rouge/lexers/fortran.rb
  lib/rouge/lexers/go.rb
  lib/rouge/lexers/groovy.rb
  lib/rouge/lexers/idlang.rb
  lib/rouge/lexers/julia.rb
  lib/rouge/lexers/m68k.rb
  lib/rouge/lexers/moonscript.rb
  lib/rouge/lexers/nim.rb
  lib/rouge/lexers/plist.rb
  lib/rouge/lexers/pony.rb
  lib/rouge/lexers/praat.rb
  lib/rouge/lexers/ruby.rb
  lib/rouge/lexers/rust.rb
  lib/rouge/lexers/sql.rb
  lib/rouge/lexers/tcl.rb
  lib/rouge/lexers/toml.rb
  lib/rouge/lexers/turtle.rb
Labels: needs-review

#1182 new theme: magritte
  lib/rouge.rb
  lib/rouge/themes/magritte.rb
Labels: needs-review

#1030 Add application/problem+json and application/schema+json to json known mimetypes.
  lib/rouge/lexers/json.rb
  spec/lexers/javascript_spec.rb
Labels: author-action

#1060 lexers/haskell: Recognize hs-boot files as Haskell
  lib/rouge/lexers/haskell.rb
  spec/lexers/haskell_spec.rb
Labels: author-action

#1035 Update for Swift 4.2
  lib/rouge/lexers/swift.rb
  spec/visual/samples/swift
Labels: author-action

#1198 Allow switching between visual test themes easily
  spec/visual/templates/layout.erb
Labels: author-action

#1199 Configure Probot to close stale issues
  .github/stale.yml
  README.md
Labels: needs-review

#1205 Add reference to semantic versioning to README
  README.md
Labels: needs-review

#1027 haskell: Properly highlight promoted data constructors
  lib/rouge/lexers/haskell.rb
  spec/visual/samples/haskell
Labels: author-action

#1191 BPF Lexer
  lib/rouge/demos/bpf
  lib/rouge/lexers/bpf.rb
  spec/visual/samples/bpf
Labels: author-action

#1207 Prefer faster __dir__ instead of dirname(__FILE__)
  lib/rouge/lexer.rb
  lib/rouge/lexers/apache.rb
  lib/rouge/lexers/gherkin.rb
  lib/rouge/lexers/lasso.rb
  lib/rouge/lexers/lua.rb
  lib/rouge/lexers/mathematica.rb
  lib/rouge/lexers/matlab.rb
  lib/rouge/lexers/php.rb
  lib/rouge/lexers/sqf.rb
  lib/rouge/lexers/viml.rb
Labels: needs-review

#1192 Fix debug errors in Liquid lexer
  lib/rouge/lexers/liquid.rb
Labels: needs-review

#986 Fix function attributes and attribute groups on LLVM
  lib/rouge/lexers/llvm.rb
  spec/visual/samples/llvm
Labels: maintainer-action

#1197 Reduce Ruby warnings
  lib/rouge/guessers/glob_mapping.rb
  lib/rouge/lexers/apple_script.rb
  lib/rouge/lexers/bsl.rb
  lib/rouge/lexers/ceylon.rb
  lib/rouge/lexers/elixir.rb
  lib/rouge/lexers/glsl.rb
  lib/rouge/lexers/groovy.rb
  lib/rouge/lexers/haml.rb
  lib/rouge/lexers/m68k.rb
  lib/rouge/lexers/make.rb
  lib/rouge/lexers/nasm.rb
  lib/rouge/lexers/powershell.rb
  lib/rouge/lexers/prolog.rb
  lib/rouge/lexers/python.rb
  lib/rouge/lexers/ruby.rb
  lib/rouge/lexers/terraform.rb
  lib/rouge/lexers/verilog.rb
Labels: author-action

#1145 Update lexer development guide
  .yardopts
  docs/LexerDevelopment.md
Labels: author-action

#1187 properly deprecate the options hash
  lib/rouge/lexer.rb
Labels: author-action

#1183 Implement the tex formatter and TexThemeRenderer
  lib/rouge.rb
  lib/rouge/cli.rb
  lib/rouge/formatters/tex.rb
  lib/rouge/tex_theme_renderer.rb
  lib/rouge/theme.rb
  spec/formatters/tex_spec.rb
Labels: needs-review

#1215 add a global 'require' option for all modes
  .rubocop.yml
  lib/rouge/cli.rb
Labels: author-action

#1196 Improve highlighting of Liquid `for .. in` tags
  lib/rouge/lexers/liquid.rb
  spec/visual/samples/liquid
Labels: needs-review

#1204 Add missing bgColor for 'monokai.sublime' theme
  lib/rouge/themes/monokai_sublime.rb
Labels: needs-review

#1224 Fix empty-color bug
  lib/rouge/tex_theme_renderer.rb
Labels: needs-review

#1206 add a `rake similarity[lexer_name]` and Similarity tester
  spec/support/similarity.rb
  tasks/similarity.rake
Labels: author-action

#1213 Feature/upgrade powershell
  lib/rouge/demos/powershell
  lib/rouge/lexers/powershell.rb
  spec/visual/samples/powershell
Labels: needs-review

#1225 Improve tokenising of numbers in Elixir lexer
  lib/rouge/lexers/elixir.rb
  spec/visual/samples/elixir
Labels: needs-review

#1200 Add OpenEdge ABL lexer
  lib/rouge/demos/openedge
  lib/rouge/lexers/openedge.rb
  spec/lexers/openedge_spec.rb
  spec/visual/samples/openedge
Labels: needs-review

#1214 Fixes #947: Add documentation on using Docker for development
  docs/DevEnvironment.md
  docs/Docker.md
Labels: author-action
