Repository rouge-ruby/rouge, pull requests merged in 2019-07, with the labels that each got.

#1229 Added single quote and 'rem' style comments.
  lib/rouge/demos/xojo
  lib/rouge/lexers/xojo.rb
  spec/visual/samples/xojo
Labels: author-action

#1089 Add XPath and XQuery lexers
  lib/rouge/demos/xpath
  lib/rouge/demos/xquery
  lib/rouge/lexers/xpath.rb
  lib/rouge/lexers/xquery.rb
  spec/lexers/xpath_spec.rb
  spec/lexers/xquery_spec.rb
  spec/visual/samples/xpath
  spec/visual/samples/xquery
Labels: needs-review

#1239 Fix num literals in YAML scalar block highlighting
  lib/rouge/lexers/yaml.rb
  spec/visual/samples/yaml
Labels: author-action

#1234 Add highlighting of block chomping in YAML text
  lib/rouge/lexers/yaml.rb
  spec/visual/samples/yaml
Labels: needs-review

#1240 Improve readability of lexer debug outputs
  lib/rouge/regex_lexer.rb
  lib/rouge/util.rb
Labels: author-action

#1238 Explain how to run a single test file with `rake`
  README.md
Labels: author-action

#1235 Fix highlighting of YAML block strings
  lib/rouge/lexers/yaml.rb
  spec/visual/samples/yaml
Labels: author-action

#976 Add highlighting for fastlane files
  lib/rouge/lexers/ruby.rb
  spec/lexers/ruby_spec.rb
Labels: author-action

#975 Add highlighting for Pipfile
  lib/rouge/lexers/json.rb
  lib/rouge/lexers/toml.rb
  spec/lexers/javascript_spec.rb
  spec/lexers/toml_spec.rb
Labels: author-action

#1247 Fix highlighting of keyword `defined?` in Ruby
  lib/rouge/lexers/ruby.rb
  spec/visual/samples/ruby
Labels: author-action

#1232 Fix usage of file paths in PowerShell lexer
  lib/rouge/lexers/powershell.rb
  spec/visual/samples/powershell
Labels: needs-review

#1211 Add new HTMLLineTable formatter
  README.md
  lib/rouge.rb
  lib/rouge/cli.rb
  lib/rouge/formatters/html_line_table.rb
  spec/formatters/html_line_table_spec.rb
  spec/visual/app.rb
  spec/visual/templates/layout.erb
Labels: author-action

#1251 Add _class and _while keywords to magik lexer
  lib/rouge/lexers/magik.rb
  spec/visual/samples/magik
Labels: author-action

#1227 Simplify Make visual sample
  lib/rouge/lexers/make.rb
  spec/visual/samples/make
Labels: needs-review

#1168 Allow juxtaposed visual test
  spec/visual/app.rb
  spec/visual/templates/layout.erb
  spec/visual/templates/lexer.erb
  spec/visual/templates/lexer_juxtaposed.erb
Labels: author-action

#973 Add missing keywords from PHP
  lib/rouge/lexers/php.rb
  lib/rouge/lexers/php/builtins.rb
  spec/lexers/php_spec.rb
  spec/visual/samples/php
Labels: author-action

#1255 Add a lexer for Ada 2012.
  lib/rouge/demos/ada
  lib/rouge/lexers/ada.rb
  spec/lexers/ada_spec.rb
  spec/visual/samples/ada
Labels: author-action

#1253 Added HOCON lexer.
  lib/rouge/demos/hocon
  lib/rouge/lexers/hocon.rb
  spec/lexers/hocon_spec.rb
  spec/visual/samples/hocon
Labels: author-action

#1261 Update the GraphQL with extend and front-matter
  lib/rouge/lexers/graphql.rb
  spec/visual/samples/graphql
Labels: author-action

#864 Add OpenTypeFeature suppport
  lib/rouge/demos/opentype_feature_file
  lib/rouge/lexers/opentype_feature_file.rb
  spec/lexers/opentype_feature_file_spec.rb
  spec/visual/samples/opentype_feature_file
Labels: author-action

#1107 Add SAS lexer and accompanying files
  lib/rouge/demos/sas
  lib/rouge/lexers/sas.rb
  spec/lexers/sas_spec.rb
  spec/visual/samples/sas
Labels: author-action

#1264 Remove italics from preprocessor style rules
  lib/rouge/themes/magritte.rb
  lib/rouge/themes/thankful_eyes.rb
  lib/rouge/themes/tulip.rb
Labels: needs-review

#963 syntax highlighting support for CUDA C++ .cu / .cuh files
  lib/rouge/demos/cuda
  lib/rouge/lexers/cuda.rb
  spec/lexers/cuda_spec.rb
  spec/visual/samples/cuda
Labels: needs-review

#957 Fix Rust attributes and doc comments on the first line
  lib/rouge/lexers/rust.rb
  spec/visual/samples/rust
Labels: needs-review

#1036 Add GDScript language support
  lib/rouge/demos/gdscript
  lib/rouge/lexers/gdscript.rb
  spec/lexers/gdscript_spec.rb
  spec/visual/samples/gdscript
Labels: author-action

#952 Correctly highlight placeholders in Gherkin syntax
  lib/rouge/lexers/gherkin.rb
  spec/lexers/gherkin_spec.rb
  spec/visual/samples/gherkin
Labels: needs-review

#899 Better handlebars support #737
  lib/rouge/lexers/handlebars.rb
  spec/visual/samples/handlebars
Labels: needs-review

#1029 JSON rewrite
  lib/rouge/lexers/hocon.rb
  lib/rouge/lexers/json.rb
  spec/lexers/javascript_spec.rb
  spec/lexers/json_spec.rb
  spec/visual/samples/json
Labels: author-action

#1265 Simplify HTML visual sample
  spec/visual/samples/html
Labels: needs-review

#907 Allow []()*. in html attribute names #725
  lib/rouge/lexers/html.rb
  spec/lexers/html_spec.rb
  spec/visual/samples/html
Labels: needs-review

#1267 Rationalise Rake tasks
  .travis.yml
  Rakefile
  tasks/builtins/gherkin.rake
  tasks/builtins/lua.rake
  tasks/builtins/mathematica.rake
  tasks/builtins/matlab.rake
  tasks/builtins/php.rake
  tasks/builtins/sqf.rake
  tasks/builtins/vim.rake
  tasks/check/memory.rake
  tasks/check/similarity.rake
  tasks/check/specs.rake
  tasks/check/style.rake
  tasks/generate/lexer.rake
  tasks/similarity.rake
  tasks/update/changelog.rake
Labels: needs-review

#1268 Remove mistaken keywords in Mason lexer
  lib/rouge/lexers/mason.rb
Labels: needs-review

#1269 Add disambiguation for C++ header files
  lib/rouge/guessers/disambiguation.rb
  lib/rouge/lexers/cpp.rb
  spec/lexers/cpp_spec.rb
Labels: needs-review

#1270 Move to self-hosted documentation
  Gemfile
  README.md
  Rakefile
  rouge.gemspec
  tasks/generate/docs.rake
Labels: needs-review

#1272 Add a Rake task to check warnings output by Ruby
  tasks/check/warnings.rake
Labels: needs-review

#1276 Disable line-number selection in HTMLLineTable
  lib/rouge/formatters/html_line_table.rb
  spec/formatters/html_line_table_spec.rb
Labels: needs-review

#1288 Fix unmatched characters in Puppet lexer
  lib/rouge/lexers/puppet.rb
  spec/visual/samples/puppet
Labels: needs-review

#903 Add support for EPP templates (#901)
  lib/rouge/demos/epp
  lib/rouge/lexers/epp.rb
  spec/lexers/epp_spec.rb
  spec/visual/samples/epp
Labels: dependent-pr

#1057 Add a lexer for ARM assembly files
  lib/rouge/demos/armasm
  lib/rouge/lexers/armasm.rb
  spec/lexers/armasm_spec.rb
  spec/visual/samples/armasm
Labels: author-action

#1285 Improvements to Make lexer
  lib/rouge/lexers/make.rb
  spec/lexers/make_spec.rb
  spec/visual/samples/make
Labels: author-action

#1271 Update README
  README.md
Labels: needs-review

#896 [Fix #895] allow numbers within variable names
  lib/rouge/lexers/r.rb
  spec/visual/samples/r
Labels: author-action

#1283 Add a lexer for MessageTrans messages files
  lib/rouge/demos/msgtrans
  lib/rouge/guessers/disambiguation.rb
  lib/rouge/lexers/msgtrans.rb
  lib/rouge/lexers/plain_text.rb
  spec/lexers/msgtrans_spec.rb
  spec/lexers/plain_text_spec.rb
  spec/visual/samples/msgtrans
Labels: author-action

#1282 Add a lexer for CMHG files
  lib/rouge/demos/cmhg
  lib/rouge/lexers/cmhg.rb
  spec/lexers/cmhg_spec.rb
  spec/visual/samples/cmhg
Labels: author-action
