Repository rouge-ruby/rouge, pull requests merged in 2020-02, with the labels that each got.

#1414 Support Unicode identifiers in Java lexer
  lib/rouge/lexers/java.rb
  spec/visual/samples/java
Labels: needs-review

#1403 Add regex support to Lua lexer
  lib/rouge/lexers/lua.rb
  spec/visual/samples/lua
Labels: needs-review

#1419 toml: implement single quote & multiline strings
  lib/rouge/lexers/toml.rb
  spec/visual/samples/toml
Labels: needs-review

#1412 allow sub-options to be passed to lexers
  lib/rouge/lexer.rb
  lib/rouge/lexers/php.rb
  spec/lexer_spec.rb
Labels: dependent-pr

#1422 Update latest Ruby checked by Travis to 2.7
  .travis.yml
Labels: needs-review

#1421 Improvements to the NASM samples
  lib/rouge/demos/nasm
  spec/visual/samples/nasm
Labels: author-action

#1415 add a guide for implementing custom HTML formatters
  README.md
Labels: needs-review

#365 Add a Varnish lexer
  lib/rouge/demos/varnish
  lib/rouge/lexers/varnish.rb
  spec/lexers/varnish_spec.rb
  spec/visual/samples/varnish
Labels: lexer-request, needs-review

#1424 Add missing @autoreleasepool to objective-c at_keywords
  lib/rouge/lexers/objective_c/common.rb
  spec/visual/samples/objective_c
Labels: author-action

#1429 Fix array access priority in PowerShell lexer
  lib/rouge/lexers/powershell.rb
  spec/visual/samples/powershell
Labels: needs-review

#1433 Clean up Varnish files
  lib/rouge/lexers/varnish.rb
  spec/lexers/varnish_spec.rb
Labels: needs-review

#1436 Update GitHub Issues settings
  .github/ISSUE_TEMPLATE/lexer-bug.md
  .github/stale.yml
Labels: needs-review

#1428 Improve NASM lexer
  lib/rouge/lexers/nasm.rb
  spec/visual/samples/nasm
Labels: needs-review

#1438 Fix symbol pattern in Scala lexer
  lib/rouge/lexers/scala.rb
  spec/visual/samples/scala
Labels: needs-review

#1441 Improve regex and string lexing in CoffeeScript lexer
  lib/rouge/lexers/coffeescript.rb
Labels: needs-review

#1442 Fix fenced code blocks in Markdown lexer
  lib/rouge/lexers/markdown.rb
  spec/visual/samples/markdown
Labels: needs-review

#1396 Add ECL lexer
  lib/rouge/demos/ecl
  lib/rouge/lexers/ecl.rb
  spec/lexers/ecl_spec.rb
  spec/visual/samples/ecl
Labels: author-action

#1445 Fix brackets in links in markdown lexer
  lib/rouge/lexers/markdown.rb
  spec/visual/samples/markdown
Labels: author-action
