Repository rouge-ruby/rouge, pull requests merged in 2020-04, with the labels that each got.

#1472 Fix use of # character in Racket lexer
  lib/rouge/lexers/racket.rb
  spec/visual/samples/racket
Labels: needs-review

#1475 Add support for optional chaining operator to TypeScript lexer
  lib/rouge/lexers/typescript.rb
  spec/visual/samples/typescript
Labels: needs-review

#1431 Fix Ruby 2.7 warnings in `check:memory` Rake task
  tasks/check/memory.rake
Labels: needs-review

#1440 Add jsonc alias to JSONDOC lexer
  lib/rouge/lexers/json_doc.rb
Labels: needs-review

#1468 rego file parser
  lib/rouge/demos/rego
  lib/rouge/lexers/rego.rb
  spec/lexers/rego_spec.rb
  spec/visual/samples/rego
Labels: author-action

#760 Add Solidity (lexer and examples)
  lib/rouge/demos/solidity
  lib/rouge/lexers/solidity.rb
  spec/lexers/solidity_spec.rb
  spec/visual/samples/solidity
Labels: author-action

#1375 Remove . as a operator in Python lexer
  lib/rouge/lexers/python.rb
  spec/visual/samples/python
Labels: maintainer-action

#1397 some updates to the PHP lexer
  lib/rouge/lexers/php.rb
  spec/lexers/php_spec.rb
  spec/visual/samples/php
Labels: author-action

#1478 Fix multiple operator rule in PHP lexer
  lib/rouge/lexers/php.rb
  spec/visual/samples/php
Labels: needs-review

#1483 Add support for slot shorthand syntax to Vue lexer
  lib/rouge/lexers/vue.rb
  spec/visual/samples/vue
Labels: needs-review

#1490 Support regular expressions in Terraform lexer
  lib/rouge/lexers/terraform.rb
  spec/visual/samples/terraform
Labels: needs-review

#1482 Support dictionary indexers on nested properties in F# lexer
  lib/rouge/lexers/fsharp.rb
  spec/visual/samples/fsharp
Labels: needs-review

#1488 Simplify default rule in YANG lexer
  lib/rouge/lexers/yang.rb
  spec/lexers/yang_spec.rb
Labels: author-action

#1481 Use namespaced loaders rather than method with global scope
  lib/rouge.rb
Labels: needs-review

#1495 Improve consistency of lexing of class-like names in C++ lexer
  lib/rouge/lexers/cpp.rb
  spec/visual/samples/cpp
Labels: needs-review

#1387 GHC Cmm
  lib/rouge/demos/ghc-cmm
  lib/rouge/lexers/ghc_cmm.rb
  spec/lexers/ghc_cmm_spec.rb
  spec/visual/samples/ghc-cmm
Labels: author-action

#1497 Allow incorrect braces and brackets in JSON lexer
  lib/rouge/lexers/json.rb
  spec/visual/samples/json
Labels: needs-review

#1496 Add support for labels to Kotlin lexer
  lib/rouge/lexers/kotlin.rb
  spec/lexers/kotlin_spec.rb
  spec/visual/samples/kotlin
Labels: author-action

#1498 Tokenise error messages in Console lexer
  lib/rouge/lexers/console.rb
  spec/lexers/console_spec.rb
Labels: needs-review

#1418 Pre-generate builtins and keywords for lexers
  lib/rouge/lexers/apache.rb
  lib/rouge/lexers/apache/keywords.rb
  lib/rouge/lexers/lasso.rb
  lib/rouge/lexers/lasso/keywords.rb
  lib/rouge/lexers/matlab.rb
  lib/rouge/lexers/matlab/builtins.rb
  tasks/builtins/apache.rake
  tasks/builtins/apache/keywords.yml
  tasks/builtins/lasso.rake
  tasks/builtins/lasso/keywords.yml
  tasks/builtins/matlab.rake
  tasks/builtins/matlab/builtins.yml
  tasks/generate/builtins.rake
Labels: author-action

#1499 Remove Duplicate identity Keyword in YANG Lexer
  lib/rouge/lexers/yang.rb
Labels: author-action

#1477 Use generic string states in Python lexer
  lib/rouge/lexers/python.rb
  spec/visual/samples/python
Labels: needs-review

#1476 Improve lexing of ternaries that include symbols in Ruby lexer
  lib/rouge/lexers/ruby.rb
  spec/visual/samples/ruby
Labels: needs-review

#1423 Add a Cypher (Neo4j) lexer
  lib/rouge/demos/cypher
  lib/rouge/lexers/cypher.rb
  spec/lexers/cypher_spec.rb
  spec/visual/samples/cypher
Labels: author-action

#1504 Fix.kotlin.reified
  lib/rouge/lexers/kotlin.rb
  spec/lexers/kotlin_spec.rb
  spec/visual/samples/kotlin
Labels: author-action

#1505 Add missing keywords to LLVM lexer
  lib/rouge/lexers/llvm.rb
  lib/rouge/lexers/llvm/keywords.rb
  spec/visual/samples/llvm
  tasks/builtins/llvm.rake
Labels: needs-review

#1503 Use qualified method name for calls to Kernel#load
  bin/rougify
  lib/rouge.rb
  lib/rouge/lexer.rb
  lib/rouge/lexers/apache.rb
  lib/rouge/lexers/gherkin.rb
  lib/rouge/lexers/isbl.rb
  lib/rouge/lexers/lasso.rb
  lib/rouge/lexers/lua.rb
  lib/rouge/lexers/mathematica.rb
  lib/rouge/lexers/matlab.rb
  lib/rouge/lexers/php.rb
  lib/rouge/lexers/sqf.rb
  lib/rouge/lexers/viml.rb
  spec/visual/app.rb
Labels: needs-review
