Repository rouge-ruby/rouge, pull requests merged in 2020-01, with the labels that each got.

#1384 Fix division operator error
  lib/rouge/lexers/rust.rb
  spec/visual/samples/rust
Labels: needs-review

#1382 Fix parsing of 'false' as Boolean option value
  lib/rouge/lexer.rb
  spec/lexer_spec.rb
Labels: needs-review

#1332 Updates for Swift 5.1
  lib/rouge/lexers/swift.rb
  spec/visual/samples/swift
Labels: author-action

#1385 Allow spaces after Jinja filter pipes
  lib/rouge/lexers/jinja.rb
  spec/visual/samples/jinja
Labels: needs-review

#1378 Implement an Objective-C++ lexer
  lib/rouge/demos/objective_cpp
  lib/rouge/lexers/objective_c.rb
  lib/rouge/lexers/objective_c/common.rb
  lib/rouge/lexers/objective_cpp.rb
  spec/visual/samples/objective_cpp
Labels: author-action

#1386 Fix Jinja comments that contain code
  lib/rouge/lexers/jinja.rb
  spec/visual/samples/jinja
Labels: author-action

#1369 Starlark support
  lib/rouge/lexers/python.rb
  spec/lexers/python_spec.rb
Labels: author-action

#1389 Combine import and package rules in Java lexer
  lib/rouge/lexers/java.rb
Labels: needs-review

#1394 D: Add __FILE_FULL_PATH__ to keywords_pseudo
  lib/rouge/lexers/d.rb
Labels: needs-review

#1402 fix crash in terminal256 formatter with escaped tokens
  lib/rouge/formatters/terminal256.rb
  spec/lexers/escape_spec.rb
Labels: needs-review

#1400 Remove sprintf format parsing for Rust lexer
  lib/rouge/lexers/rust.rb
  spec/visual/samples/rust
Labels: needs-review

#1399 Support raw strings in Rust lexer
  lib/rouge/lexers/rust.rb
  spec/visual/samples/rust
Labels: needs-review

#1393 Support optional props in TypeScript lexer
  lib/rouge/lexers/typescript.rb
  spec/visual/samples/typescript
Labels: discussion-open

#1411 Support '"' to identify heredoc delimiters in Shell lexer
  lib/rouge/lexers/shell.rb
  spec/visual/samples/shell
Labels: needs-review

#1406 Fix NameError on @ + UPPERCASE token in Objective-C
  lib/rouge/lexers/objective_c/common.rb
  spec/visual/samples/objective_c
Labels: author-action

#1413 Feature.terminal truecolor
  lib/rouge.rb
  lib/rouge/cli.rb
  lib/rouge/formatters/terminal256.rb
  lib/rouge/formatters/terminal_truecolor.rb
  spec/formatters/terminal_truecolor_spec.rb
Labels: author-action
