Repository rouge-ruby/rouge, pull requests merged in 2020-10, with the labels that each got.

#1586 Support quoting structs/tables in Janet lexer
  lib/rouge/lexers/janet.rb
  spec/visual/samples/janet
Labels: needs-review

#1426 resolves #264 add line highlighting option
  README.md
  lib/rouge.rb
  lib/rouge/formatters/html_line_highlighter.rb
  spec/formatters/html_line_highlighter_spec.rb
Labels: maintainer-action

#1567 Add a lexer for emails
  lib/rouge/demos/email
  lib/rouge/lexers/email.rb
  spec/lexers/email_spec.rb
  spec/visual/samples/email
Labels: author-action

#1606 Fix errors from new empty regex requirements
  lib/rouge/lexers/apex.rb
  lib/rouge/lexers/email.rb
  lib/rouge/lexers/j.rb
Labels: needs-review

#1594 js: add a special case for safe navigation
  lib/rouge/lexers/javascript.rb
  spec/visual/samples/javascript
Labels: needs-review

#1605 Fix handling of square parentheses in velocity lexer
  lib/rouge/lexers/velocity.rb
  spec/visual/samples/velocity
Labels: needs-review
