Repository rouge-ruby/rouge, pull requests merged in 2022-01, with the labels that each got.

#1762 fixes #1760
  lib/rouge/lexers/kotlin.rb
  spec/visual/samples/kotlin
Labels: needs-review

#1735 Add Stan Lexer
  docs/Languages.md
  lib/rouge/demos/stan
  lib/rouge/lexers/stan.rb
  spec/lexers/stan_spec.rb
  spec/visual/samples/stan
Labels: author-action

#1779 don't crash if last line of console snippet ends with \
  lib/rouge/lexers/console.rb
  spec/lexers/console_spec.rb
Labels: author-action

#1658 Stata lexer added
  lib/rouge/demos/stata
  lib/rouge/lexers/stata.rb
  spec/lexers/stata_spec.rb
  spec/visual/samples/stata
Labels: needs-review, author-action

#1696 Fix Visual Test App on Ruby 3.0
  Gemfile
Labels: author-action

#1649 Rust: update lexer for the latest version of Rust
  lib/rouge/lexers/rust.rb
  spec/visual/samples/rust
Labels: needs-review

#1697 Add lexer for Fluent
  lib/rouge/demos/fluent
  lib/rouge/lexers/fluent.rb
  spec/lexers/fluent_spec.rb
  spec/visual/samples/fluent
Labels: needs-review

#1710 Support Cypher multi-line comments
  lib/rouge/lexers/cypher.rb
  spec/lexers/cypher_spec.rb
  spec/support/lexing.rb
  spec/visual/samples/cypher
Labels: author-action

#1691 Partially update Dart lexer with newer keywords and types
  lib/rouge/lexers/dart.rb
Labels: needs-review

#1769 Add HCL file extensions
  lib/rouge/lexers/hcl.rb
Labels: needs-review

#1650 JSX: Allow dashes in attribute names
  lib/rouge/lexers/jsx.rb
  spec/lexers/jsx_spec.rb
Labels: needs-review

#1654 Fix SPARQL unicode names support (fix #1653)
  lib/rouge/lexers/sparql.rb
  spec/visual/samples/sparql
Labels: author-action
