Repository rouge-ruby/rouge, pull requests merged in 2022-06, with the labels that each got.

#1682 Feature.isabelle lexer
  docs/Languages.md
  lib/rouge/demos/isabelle
  lib/rouge/lexers/isabelle.rb
  spec/lexers/isabelle_spec.rb
  spec/visual/samples/isabelle
Labels: needs-review, author-action

#1829 PHP: support new syntax (constructor property promotion, readonly modifier, etc.)
  lib/rouge/lexers/php.rb
  spec/visual/samples/php
Labels: needs-review

#1836 Support more Jenkins pipeline name variations in groovy lexer
  lib/rouge/lexers/groovy.rb
  spec/lexers/groovy_spec.rb
Labels: author-action

#1838 Dart: Distinguish between punctuation and operators
  lib/rouge/lexers/dart.rb
Labels: needs-review, author-action
